echo Test L96 ...
python main.py inputL96 
echo Test KS ...
python main.py inputKS 
echo Test KSFrontBack ...
python main.py inputKSFrontBack
echo Test L96FrontBack ...
python main.py inputL96FrontBack
